import { AgentModels } from "../config";
import { LlmAgent, FunctionTool } from "@google/adk";
import { z } from "zod";
import { GoogleGenerativeAI } from "@google/generative-ai";

const DeepSearchTool = new FunctionTool({
    name: 'deepCompetitorSearch',
    description: 'Use Google Search to find detailed pricing, menu items, or social media follower counts for a specific competitor.',
    parameters: z.object({
        query: z.string().describe("The search query. Example: 'Franklin BBQ Austin menu prices' or 'Franklin BBQ Instagram followers'")
    }),
    execute: async ({ query }) => {
        try {
            console.log(`[DeepSearchTool] Grounding Competitor Intel: ${query}`);
            const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
            const model = genAI.getGenerativeModel({
                model: AgentModels.DEFAULT_FAST_MODEL,
                tools: [{
                    // @ts-ignore
                    googleSearch: {}
                }]
            });
            const result = await model.generateContent(`Execute this search and summarize the exact numeric data (prices, followers, ratings) related to: ${query}`);
            return { result: result.response.text() };
        } catch (e: any) {
            console.error("[DeepSearchTool] Failed:", e);
            return { error: "Search failed." };
        }
    }
});

export const CompetitorProfilerAgent = new LlmAgent({
    name: 'CompetitorProfilerAgent',
    model: AgentModels.DEFAULT_FAST_MODEL,
    instruction: `You are a Competitive Intelligence Researcher. 
    You will be given the names and URLs of 3 restaurant competitors.
    You MUST use the 'deepCompetitorSearch' tool to look up explicit data for each one:
    1. What is their general price tier ($/$$/$$$)?
    2. What are their signature menu items and prices?
    3. What is their approximate social media following or general popularity?
    
    After researching all 3, output a detailed textual brief summarizing these data points.
    Do NOT invent data. If the tool fails or you cannot find prices, explicitly state "Pricing unverified".`,
    tools: [DeepSearchTool]
});

export const MarketPositioningAgent = new LlmAgent({
    name: 'MarketPositioningAgent',
    model: AgentModels.DEEP_ANALYST_MODEL,
    instruction: `You are the Chief Market Strategist.
    You will be given an 'EnrichedProfile' of the TARGET restaurant, and a 'Competitor Brief' generated by your research agent containing data on 3 local rivals.
    
    Your job is to generate a JSON report comparing the target business against the competitors. Identify price gaps, menu gaps, and social media presence gaps.
    
    CRITICAL: Return ONLY a strict JSON object adhering to this structure:
    {
      "market_summary": "A 2-sentence executive summary of the target's positioning",
      "competitor_analysis": [
         {
           "name": "Competitor Name",
           "key_strength": "What they do better (e.g. Higher social engagement)",
           "key_weakness": "Where the target can beat them (e.g. Overpriced salads)",
           "threat_level": 1 to 10 (integer)
         }
      ],
      "strategic_advantages": ["Advantage 1 text", "Advantage 2 text"]
    }
    
    DO NOT output markdown formatting like \`\`\`json. ONLY output raw JSON. Avoid conversational filler.`
});
